name: gh-productivity
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pandas>=2.0
  - requests>=2.31
  - matplotlib>=3.7
  - seaborn>=0.12
  - pip
  - pip:
      - plotly>=5.20
